#!/bin/bash
#########################################################################
# THIS IS PROVIDED "AS IS", WITHOUT ANY WARRANTY, AND WITHOUT ANY SUPPORT. 
# LICENSE : CC-BY-SA 3.0 - http://creativecommons.org/licenses/by-sa/3.0/ 
# PFX Poller File eXchange
# Test with CentOS 6 / Centreon 2.6 / Nagios 3.5.1
# Scripts to tranfert Nagios configuration in FTP
#########################################################################
###################################################
# lib                                             #
# Auteur :   Matthieu PERRIN (OBS)                #
# Fonction : execute tout les .sh de lib/         #
###################################################

dir=$(dirname "${BASH_SOURCE[0]}")
pushd $dir > /dev/null 2>&1

for file in *.sh ; do
  if [ -f "$file" ] ; then
    . "$file"
    #echo "$file"
  fi
done

popd > /dev/null 2>&1
